variable "tenancy_ocid" {}
variable "compartment_ocid" {}
variable "ssh_private_key_path" {}
variable  "node-1-private-ip" {}
variable  "node-1-public-ip" {}
variable  "node-2-private-ip" {}
variable  "node-2-public-ip" {}
variable  "node-3-private-ip" {}
variable  "node-3-public-ip" {}
